INSERT INTO USERS(ID,USERNAME) VALUES(1,'JOEY');
INSERT INTO USERS (ID,USERNAME) VALUES (2,'PETER');
INSERT INTO USERS (ID,USERNAME) VALUES (3,'WANDA');
INSERT INTO USERS (ID,USERNAME) VALUES (4,'NAME');